---

- hosts: raspberrypi
  vars_files:
    - host_vars/host_maps.yml
  vars: 
    ansible_shell_allow_world_readable_temp: true 
    pipelining: True

  roles:
    - common
    - rpi
    - supervisor