# Example of users.yml which you may want to encrypt using ansible-vault.
#
# Users that must be present on the system
#
create_users:
  - name: elfgirl
    comment: "ElfGirl"
    uid: 1024
    group: users
    # don't include the group from 'group:' above in the 'groups:' below; this
    # breaks idempotency for some reason
    groups: "adm,dialout,sudo,audio,video,plugdev,games,input,netdev,spi,i2c,gpio"
    pubkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJbaLaNo3rCZTgm2ZFIEDYJ6Qh71jXAEr0JTrjhqmV49Vg8xcXRwooNs+Ehc77P4A15mmgaHCWakMTPQpFi12bQdjuaSqDQR6z7/ADXhhdVDJVDaiZKrNxp0sx/VwOScKkVT9YWwc2Dl+11HqobRsKseUhagD4wBZfPgcCOruCpYJVVhnAtxTh//sAjzb5JHkjZRm2dqqh5mzu/irpMukFNDcDe71htoQhZMERRQHjJcKerSeHpw5/B98CVX8/71M99d1aPXVYO9f1lRGBMuItAiUORw1rPQOJ7IlK8amc7sZhrmEdoDl5G9dhF01csy+hEHFRU3VCnIwgODJPHf8XHXIC9GSk+CJUgRr8Oqh+Dfi2sELRjglFGYI4ddBxXc9IHb4GWVTNpKqoELlKclkCDj5NztCLh9jmdWTqL63FqIqXrD/ReqKtTrQztSNrePXWOOWUCPwPKcWBUDqltFrjRerA84/9SekrFNGHoMl+0PTHjV//aw3r+W9bUWu9mFmQpFiq6KNovmE+ptZ4BB1+P5rVhSdY+McROBE6i0Keo9H6ANRR26Fojdqo2XK2x2jdRkvu9dRddGgKOcqc954iQvn0XLeEO0AO2QvlFhhcqjFkDd0NDSXDmKq+3nqqRmDgS8hGnhJ1XsH3cePNKN27+h1o8rOvs6M38xTiH3Pc4w=="

  - authorized_key:
    user: elfgirl
    state: present
    manage_dir: yes
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJbaLaNo3rCZTgm2ZFIEDYJ6Qh71jXAEr0JTrjhqmV49Vg8xcXRwooNs+Ehc77P4A15mmgaHCWakMTPQpFi12bQdjuaSqDQR6z7/ADXhhdVDJVDaiZKrNxp0sx/VwOScKkVT9YWwc2Dl+11HqobRsKseUhagD4wBZfPgcCOruCpYJVVhnAtxTh//sAjzb5JHkjZRm2dqqh5mzu/irpMukFNDcDe71htoQhZMERRQHjJcKerSeHpw5/B98CVX8/71M99d1aPXVYO9f1lRGBMuItAiUORw1rPQOJ7IlK8amc7sZhrmEdoDl5G9dhF01csy+hEHFRU3VCnIwgODJPHf8XHXIC9GSk+CJUgRr8Oqh+Dfi2sELRjglFGYI4ddBxXc9IHb4GWVTNpKqoELlKclkCDj5NztCLh9jmdWTqL63FqIqXrD/ReqKtTrQztSNrePXWOOWUCPwPKcWBUDqltFrjRerA84/9SekrFNGHoMl+0PTHjV//aw3r+W9bUWu9mFmQpFiq6KNovmE+ptZ4BB1+P5rVhSdY+McROBE6i0Keo9H6ANRR26Fojdqo2XK2x2jdRkvu9dRddGgKOcqc954iQvn0XLeEO0AO2QvlFhhcqjFkDd0NDSXDmKq+3nqqRmDgS8hGnhJ1XsH3cePNKN27+h1o8rOvs6M38xTiH3Pc4w=="
