---
# Self identify and load config - this allows the playbook to run on either
# localhost or a remote host
- name: "load config : store MAC address for eth0"
  set_fact:
    my_macaddr: "{{ hostvars[inventory_hostname].ansible_eth0.macaddress }}"
  when: "'ansible_eth0' in hostvars[inventory_hostname]"
  tags:
    - always
    
# Raspberry Pi Zero W has no eth0, so fall back to wlan0
- name: "load config : store MAC address for wlan0"
  set_fact:
    my_macaddr: "{{ hostvars[inventory_hostname].ansible_wlan0.macaddress }}"
  when: "my_macaddr is not defined"
  tags:
    - always

# for model A, we cannot proceed because there is no mac address

- name: "load config : load raspberry pi configuration for {{ my_macaddr }} {{ macaddrs[my_macaddr] }} "
  include_vars:
    file: "../../../host_vars/{{ macaddrs[my_macaddr] }}.yml"
  tags:
    - always
    
- name: "load config : assert that configuration is loaded"
  assert:
    that:
      - "raspi_hostname | default(false)"

- name: "load config : Verify hostname"
  debug:
    msg: "loaded configuration for {{ raspi_hostname }}"
