---
# Install required software
- name: "python : install python material for Raspberry Pi"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - python3-gpiozero
      - python3-inkyphat
      - python3-picamera
      - smbus         
      - adafruit-blinka
      - adafruit-circuitpython-mcp3xxx
      - adafruit-circuitpython-ads1x15

  tags:
    - python

- name: "python : now the pip installs"
  pip:
    name:
      - gunicorn
      - sqlalchemy
    executable: pip3
  tags:
    - python