---
# Install required software

- name: "python : now the pip installs"
  pip:
    name:
      - gunicorn
      - supervisor
      - sqlalchemy
      - smbus         
      - adafruit-blinka
      - adafruit-circuitpython-mcp3xxx
      - adafruit-circuitpython-ads1x15
    executable: pip3

- name: "python : install additional host-specific python"
  pip:
    name: "{{ host_pip_software | default([]) }}"
    executable: pip3

