---
# Install required software
- name: "software : install software for Raspberry Pi"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - python-pip
      - python3-pip
      - gpiod
  tags:
    - sw

# Uninstall Raspbian bloat
- name: "software : remove raspbian bloat"
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - wolfram-engine
      - libreoffice*
      - scratch
      - minecraft-pi
      - python-minecraftpi 
      - python3-minecraftpi
      - sonic-pi
      - dillo
      - gpicview
      - penguinspuzzle
  tags:
    - sw

- name: "software : Remove useless packages from the cache"
  apt:
    autoclean: yes
  tags:
    - sw