---
# Install required software
- name: "software : install software for Raspberry Pi"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - gpiod
      - i2c-tools
      - libi2c-dev
      #- python-smbus
      - python3-smbus


# Uninstall Raspbian bloat
- name: "software : remove raspbian bloat"
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - wolfram-engine
      - libreoffice*
      - scratch
      - minecraft-pi
      - python-minecraftpi 
      - python3-minecraftpi
      - sonic-pi
      - dillo
      - gpicview
      - penguinspuzzle


- name: "software : install additional host-specific software"
  apt:
    name: "{{ host_apt_software | default([]) }}"
    state: present
    update_cache: yes


- name: "software : Remove useless packages from the cache"
  apt:
    autoclean: yes
