---
timezone: "America/Los_Angeles"
locale: "en_US.UTF-8"
raspi_hostname: "clackberry"
raspi_domain: "local"
xkblayout: "us"
wifi_country: "US"
enable_gui: False
enable_autologin: False
enable_bootwait: False
enable_bootsplash: False
enable_camera: True
enable_vnc: False
enable_spi: True
enable_i2c: True
enable_serial: True
enable_serial_hw: False
enable_onewire: False
enable_rgpio: True
systemd_default_target: multi-user
host_apt_software:
  - python3-yaml

host_pip_software :
  - uwsgi
  - inky

host_ports :  []

# NOTE ANY PRIVATE OR UNACCESIBLE HTTP REPOS WILL HANG ANSIBLE

default_projects: 
  - { name : 'pyLadies-SC', repo : 'https://github.com/elfgirl/pyLadies-SC.git' }
  - { name : 'RPi_Cam_Web_Interface', repo : 'https://github.com/silvanmelchior/RPi_Cam_Web_Interface.git' }