---
timezone: "America/Los_Angeles"
locale: "en_US.UTF-8"
raspi_hostname: "quackberry"
raspi_domain: "local"
xkblayout: "us"
wifi_country: "US"
enable_gui: False
enable_autologin: False
enable_bootwait: False
enable_bootsplash: False
enable_camera: True
enable_vnc: False
enable_spi: True
enable_i2c: True
enable_serial: True
enable_serial_hw: False
enable_onewire: False
enable_rgpio: True
systemd_default_target: multi-user

host_apt_software:
  - python3-yaml

host_pip_software :
  - uwsgi
  - inky

host_ports : []

host_supervisor_apps :
  - name : waterer,
    app_exec : ServerWater.py 
    app_user : pi
    repo : 'https://elfgirl:{{pat_pinecrest}}@github.com/elfgirl/pinecrest.git'


# NOTE ANY PRIVATE OR UNACCESIBLE HTTP REPOS WILL HANG ANSIBLE

pat_pinecrest: "" # Should be stored in ansible vault

default_projects: 
  - { name : 'pinecrest', repo : 'https://elfgirl:{{pat_pinecrest}}@github.com/elfgirl/pinecrest.git'}


